### ISSUE TITLE
Scanner token too large

### ISSUE THREAD

**Issue by ejianu** [DataReply/korgi#2]
Error: bufio.Scanner: token too long

Happened when intentionally breaking a chart

**Comment by ig0rsky** [comment]
![c39aa0aeabf4ccbc405b81bd473db7e2](https://user-images.githubusercontent.com/6079113/89474854-0739b280-d787-11ea-92f7-ff97d34811dd.jpg)

**Comment by ejianu** [comment]
![image](https://user-images.githubusercontent.com/57224408/89500063-556ba780-d7c1-11ea-8ef6-1562f4c96855.png)

**Comment by Arttii** [comment]
@ejianu Can you test a version from the #3 to see if that solves the issue? Or please provide a way to reproduce it, so we can test

**Comment by ejianu** [comment]
worked, I can now see the ginormous error 
thank you

For reference, it happened when trying to install this [chart](https://github.com/cetic/helm-nifi) and removing all references to 
```
registry:
  ## If true, install the Nifi registry
  enabled: true
```
in all values files
